apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-canary
  labels:
    app: my-app
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      track: canary
  template:
    metadata:
      labels:
        app: my-app
        track: canary
    spec:
      containers:
        - name: app
          image: nginx:1.25
          ports:
            - containerPort: 80